import type { Lender } from "./schema";

/**
 * Sample preferred lenders (Northeast Ohio) so the directory renders before a
 * database is wired. Institutions are real regional lenders; contacts are
 * illustrative (example.com).
 */
export const seedLenders: Lender[] = [
  {
    id: "l1111111-1111-1111-1111-111111111111",
    institutionName: "Third Federal Savings & Loan",
    contactName: "Dana Whitfield",
    title: "Senior Loan Officer",
    email: "dana.whitfield@example.com",
    phone: "216-555-0210",
    website: "https://www.thirdfederal.com",
    nmls: "449401",
    address: { city: "Cleveland", county: "Cuyahoga", state: "OH" },
    serviceCounties: ["Cuyahoga", "Summit", "Lorain", "Lake", "Medina"],
    languages: ["en", "es"],
    loanTypes: ["conventional", "fha", "ohfa"],
    programs: [
      { name: "Home Today Program", kind: "special-rate", amount: "Below-market fixed rate", description: "Low-rate mortgage with reduced fees for qualified first-time buyers.", link: "https://www.thirdfederal.com" },
      { name: "Down-Payment Assistance Grant", kind: "grant", amount: "Up to $10,000", description: "Grant toward down payment and closing costs in eligible neighborhoods." },
    ],
    marketingBlurb: "A Cleveland institution since 1938 — low rates, low fees, and dedicated first-time-buyer programs.",
    tier: "featured",
    advertising: true,
    monthlyRate: 300,
    partnerSince: "2025-09-01",
    receivesReferrals: true,
    active: true,
    notes: "Strong first-time-buyer programs; fast pre-approvals. Bilingual (Spanish) officer available.",
    dateAdded: "2025-09-01",
    lastUpdated: "2026-06-15",
  },
  {
    id: "l2222222-2222-2222-2222-222222222222",
    institutionName: "Dollar Bank",
    contactName: "Marcus Reed",
    title: "Mortgage Loan Officer",
    email: "marcus.reed@example.com",
    phone: "216-555-0233",
    website: "https://www.dollarbank.com",
    nmls: "515585",
    address: { city: "Cleveland", county: "Cuyahoga", state: "OH" },
    serviceCounties: ["Cuyahoga", "Lorain"],
    languages: ["en", "es"],
    loanTypes: ["conventional", "fha", "ohfa"],
    programs: [
      { name: "Closing-Cost Assistance", kind: "closing-cost", amount: "Up to $5,000", description: "Assistance toward closing costs for low-to-moderate-income buyers." },
    ],
    marketingBlurb: "Community-focused lending with grants that lower your cash-to-close.",
    tier: "preferred",
    advertising: true,
    monthlyRate: 150,
    partnerSince: "2026-01-15",
    receivesReferrals: true,
    active: true,
    dateAdded: "2026-01-15",
    lastUpdated: "2026-05-20",
  },
  {
    id: "l3333333-3333-3333-3333-333333333333",
    institutionName: "The Huntington National Bank",
    contactName: "Aaliyah Karim",
    title: "Loan Officer",
    email: "aaliyah.karim@example.com",
    phone: "330-555-0247",
    website: "https://www.huntington.com",
    nmls: "402436",
    address: { city: "Akron", county: "Summit", state: "OH" },
    serviceCounties: ["Summit", "Stark", "Portage", "Medina"],
    languages: ["en", "ar"],
    loanTypes: ["conventional", "fha", "va", "usda"],
    programs: [
      { name: "Home Ownership Grant", kind: "grant", amount: "Up to $7,500", description: "Grant for down payment and closing costs; no repayment required." },
    ],
    marketingBlurb: "Full-service lending across Summit and Stark counties, with an Arabic-speaking officer.",
    tier: "preferred",
    advertising: false,
    receivesReferrals: true,
    active: true,
    notes: "Arabic-speaking loan officer — great fit for referrals from our Arabic-speaking learners.",
    dateAdded: "2026-02-10",
    lastUpdated: "2026-06-01",
  },
  {
    id: "l4444444-4444-4444-4444-444444444444",
    institutionName: "KeyBank",
    contactName: "Wei Chen",
    title: "Community Mortgage Loan Officer",
    email: "wei.chen@example.com",
    phone: "216-555-0261",
    website: "https://www.key.com",
    nmls: "399797",
    address: { city: "Cleveland", county: "Cuyahoga", state: "OH" },
    serviceCounties: ["Cuyahoga", "Lake", "Geauga"],
    languages: ["en", "zh"],
    loanTypes: ["conventional", "fha", "ohfa"],
    programs: [
      { name: "Neighbors First Credit", kind: "closing-cost", amount: "Up to $5,000", description: "Credit toward closing costs in eligible communities." },
      { name: "KeyBank Special Purpose Credit", kind: "grant", amount: "Up to $5,000", description: "Down-payment/closing grant for eligible buyers." },
    ],
    marketingBlurb: "Community lending with closing-cost credits and a Mandarin-speaking officer.",
    tier: "standard",
    advertising: false,
    receivesReferrals: true,
    active: true,
    dateAdded: "2026-03-05",
    lastUpdated: "2026-05-28",
  },
];
