import type { Participant } from "./schema";

/** Fictional sample participants so the CRM renders before Supabase is wired. */
export const seedParticipants: Participant[] = [
  {
    id: "a1111111-1111-1111-1111-111111111111",
    org: "benjamin-rose",
    firstName: "Maria",
    lastName: "Gomez",
    email: "maria.g@example.com",
    phone: "216-555-0101",
    address: { city: "Cleveland", county: "Cuyahoga", state: "OH", zip: "44109" },
    preferredLanguage: "es",
    preferredFormats: ["audio", "in-person"],
    contactChannels: ["phone", "email"],
    doNotContact: false,
    household: { size: 3, annualIncome: 52000, amiPercent: 72, creditBand: "640-699", firstTimeBuyer: true, targetPurchasePrice: 180000 },
    tracks: ["first-time-buyer"],
    stage: "graduated",
    assignedCounselor: "Counselor Rivera",
    moduleProgress: [
      { moduleId: "budgeting", status: "completed", completedDate: "2026-01-15", format: "in-person" },
      { moduleId: "credit-basics", status: "completed", completedDate: "2026-01-22", format: "audio", score: 92 },
      { moduleId: "mortgages", status: "completed", completedDate: "2026-02-01", format: "in-person" },
      { moduleId: "shopping", status: "completed", completedDate: "2026-02-08", format: "in-person" },
      { moduleId: "closing", status: "completed", completedDate: "2026-02-12", format: "audio", score: 88 },
    ],
    certificates: [
      { name: "HUD Pre-Purchase Homebuyer Education", issuedDate: "2026-02-12", phase: "pre-purchase" },
    ],
    communications: [
      { id: "c1", date: "2026-02-13", channel: "phone", direction: "outbound", subject: "Graduation follow-up", body: "Congratulated on completing the certificate; discussed next steps and DPA options.", byUser: "Counselor Rivera" },
    ],
    tags: ["spanish-speaking", "ready-to-buy"],
    source: "class",
    consentToShare: true,
    consentDate: "2026-02-13",
    notes: "Pre-approved with Third Federal. Strong candidate for OHFA Your Choice! DPA.",
    dateAdded: "2026-01-10",
    lastUpdated: "2026-02-13",
  },
  {
    id: "a2222222-2222-2222-2222-222222222222",
    org: "esop",
    firstName: "Darnell",
    lastName: "Washington",
    phone: "216-555-0144",
    address: { city: "Euclid", county: "Cuyahoga", state: "OH", zip: "44117" },
    preferredLanguage: "en",
    preferredFormats: ["podcast", "pdf"],
    contactChannels: ["sms"],
    doNotContact: false,
    household: { size: 1, annualIncome: 38000, creditBand: "below-580", firstTimeBuyer: true },
    tracks: ["credit-repair", "first-time-buyer"],
    stage: "in-progress",
    moduleProgress: [
      { moduleId: "budgeting", status: "completed", completedDate: "2026-03-05", format: "podcast" },
      { moduleId: "credit-basics", status: "in-progress" },
      { moduleId: "credit-repair", status: "in-progress" },
    ],
    certificates: [],
    communications: [
      { id: "c2", date: "2026-03-06", channel: "sms", direction: "outbound", body: "Sent budgeting podcast link + next module.", byUser: "Counselor Rivera" },
    ],
    tags: ["credit-building"],
    source: "web",
    consentToShare: false,
    notes: "Needs to raise score above 620 before DPA eligibility. On a credit-repair plan.",
    dateAdded: "2026-02-28",
    lastUpdated: "2026-03-06",
  },
  {
    id: "a3333333-3333-3333-3333-333333333333",
    org: "esop",
    firstName: "Tobias",
    lastName: "Miller",
    email: "tobias.m@example.com",
    phone: "440-555-0199",
    address: { city: "Lakewood", county: "Cuyahoga", state: "OH", zip: "44107" },
    preferredLanguage: "en",
    preferredFormats: ["in-person"],
    contactChannels: ["phone", "mail"],
    doNotContact: false,
    household: { size: 4, annualIncome: 61000, creditBand: "640-699" },
    tracks: ["foreclosure-prevention"],
    stage: "enrolled",
    assignedCounselor: "Counselor Pratt",
    moduleProgress: [
      { moduleId: "default-basics", status: "completed", completedDate: "2026-04-03", format: "in-person" },
      { moduleId: "loss-mitigation", status: "in-progress" },
    ],
    certificates: [],
    communications: [
      { id: "c3", date: "2026-04-02", channel: "in-person", direction: "inbound", subject: "Intake", body: "Behind 2 payments; exploring loss-mitigation with servicer.", byUser: "Counselor Pratt" },
    ],
    tags: ["at-risk"],
    source: "referral",
    consentToShare: false,
    notes: "Foreclosure prevention case. Stabilize first; may pursue purchase later.",
    dateAdded: "2026-04-01",
    lastUpdated: "2026-04-03",
  },
  {
    id: "a4444444-4444-4444-4444-444444444444",
    org: "benjamin-rose",
    firstName: "Aisha",
    lastName: "Rahman",
    email: "aisha.r@example.com",
    address: { city: "Columbus", county: "Franklin", state: "OH", zip: "43215" },
    preferredLanguage: "ar",
    preferredFormats: ["slideshow", "large-print"],
    contactChannels: ["email"],
    doNotContact: false,
    household: { size: 2, annualIncome: 47000, amiPercent: 64, creditBand: "700-749", firstTimeBuyer: true, targetPurchasePrice: 165000 },
    tracks: ["first-time-buyer"],
    stage: "referred",
    assignedCounselor: "Counselor Rivera",
    moduleProgress: [
      { moduleId: "budgeting", status: "completed", completedDate: "2025-11-10", format: "slideshow" },
      { moduleId: "credit-basics", status: "completed", completedDate: "2025-11-15", format: "slideshow", score: 95 },
      { moduleId: "mortgages", status: "completed", completedDate: "2025-11-20", format: "slideshow" },
      { moduleId: "shopping", status: "completed", completedDate: "2025-11-28", format: "slideshow" },
      { moduleId: "closing", status: "completed", completedDate: "2025-12-02", format: "slideshow", score: 90 },
    ],
    certificates: [
      { name: "HUD Pre-Purchase Homebuyer Education", issuedDate: "2025-12-02", phase: "pre-purchase" },
    ],
    communications: [
      { id: "c4", date: "2025-12-03", channel: "email", direction: "outbound", subject: "Referral to Golden Group", body: "Consent received; referred to agent Priya Sharma.", byUser: "Counselor Rivera" },
    ],
    tags: ["arabic-speaking", "ready-to-buy"],
    source: "class",
    consentToShare: true,
    consentDate: "2025-12-03",
    referralId: "33333333-3333-3333-3333-333333333333",
    notes: "Graduated and referred. Looking in Franklin County up to $165k.",
    dateAdded: "2025-10-30",
    lastUpdated: "2025-12-03",
  },
];
